catalog:
  "@mapbox/polyline": ^1.1.1
  "@styled-icons/bootstrap": ^10.34.0
  "@styled-icons/fa-regular": ^10.34.0
  "@styled-icons/fa-solid": ^10.34.0
  "@styled-icons/foundation": ^10.34.0
  "@types/flat": ^5.0.2
  date-fns: ^2.28.0
  date-fns-tz: ^3.2.0
  flat: ^5.0.2
  maplibre-gl: ^5.6.1
  react: ^18.2.0
  react-animate-height: ^3.0.4
  react-dom: ^18.2.0
  react-intl: ^6.8.4
  react-map-gl: ^8.0.4
  styled-components: ^5.3.0
  styled-icons: ^10.34.0
onlyBuiltDependencies:
  - "@swc/core"
  - core-js
  - esbuild
  - fsevents
  - husky
  - msw
  - nx
  - puppeteer
  - unrs-resolver
packages:
  - packages/*
