allowBuilds:
  "@swc/core@1.7.42": true
  core-js@2.6.12: true
  esbuild@0.25.5: true
  fsevents@1.2.13: true
  fsevents@2.3.3: true
  husky@2.7.0: true
  msw@2.6.0: true
  nx@20.0.7: true
  puppeteer: true
  unrs-resolver@1.11.1: true
allowGit: none
catalog:
  "@mapbox/polyline": ^1.1.1
  "@styled-icons/bootstrap": ^10.34.0
  "@styled-icons/fa-regular": ^10.34.0
  "@styled-icons/fa-solid": ^10.34.0
  "@styled-icons/foundation": ^10.34.0
  "@styled-icons/styled-icon": ^10.7.1
  "@types/flat": ^5.0.2
  date-fns: ^3.6.0
  date-fns-tz: ^3.2.0
  flat: ^5.0.2
  maplibre-gl: ^5.6.1
  react: ^18.2.0
  react-animate-height: ^3.0.4
  react-dom: ^18.2.0
  react-intl: ^6.8.4
  react-map-gl: ^8.0.4
  styled-components: ^5.3.0
  styled-icons: ^10.34.0
ignoreScripts: true
minReleaseAge: 7
nodeLinker: hoisted
overrides:
  playwright: 1.60.0
  playwright-core: 1.60.0
packages:
  - packages/*
preferOffline: false
saveExact: true
strictPeerDependencies: false
